---
title: 'VOC Identification in Tarragona Measurements'
author: "Tecla Duran Fort"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: yes
    toc_depth: 3
    number_sections: no    
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
always_allow_html: true
---

```{r setup}
library(openxlsx)
library(dplyr)
library(reshape2)
library(ggplot2)
library(rprojroot)
knitr::opts_knit$set(root.dir = rprojroot::find_root(rprojroot::is_git_root))
source("../../../load_tools.R")
```

## Load Data

```{r load-data, echo=FALSE}
# Define the root folder
root_folder <- "data/raw/tgn_results_gcims/urine"

# Llista les carpetes que comencen per "results_"
folders <- list.dirs(root_folder, full.names = TRUE, recursive = FALSE)
results_folders <- folders[grepl("results_\\d{4}-\\d{2}-\\d{2}_\\d{2}-\\d{2}", folders)]

# Ordena per data (ordre descendent) i selecciona l'última
latest_folder <- sort(results_folders, decreasing = TRUE)[1]
cat("Results:", latest_folder)

# Llegeix els fitxers
cluster_stats <- read.csv(file.path(latest_folder, "all_results/cluster_stats_tgn.csv"))
peak_table_corrected <- read.csv(file.path(latest_folder, "all_results/peak_table_corrected_tgn.csv"))
peak_table_imputed <- read.csv(file.path(latest_folder, "all_results/peak_table_imputed_tgn.csv"))

```

## Target VOCs

```{r target-vocs, echo=FALSE}
target_vocs <- data.frame(
  compound = c(
    "Anisole (Monomer)",
    "2-Heptanone (Monomer)", "2-Heptanone (Dimer)",
    "2-Decanone (Monomer)", "2-Decanone (Dimer)",
    "2-Pentanone (Monomer)", "2-Pentanone (Dimer)"
  ),
  dt = c(8.692, 10.300, 13.50, 12.099, 16.296, 9.200, 11.200),
  rt = c(446.450, 414.620, 415.750, 1520, 1520, 228.240, 229.240)
)
```

## Identification

```{r identify-vocs, echo=FALSE}
relevant_clusters <- identify_target_vocs(cluster_stats, target_vocs, max_distance = 0.2, ratio = 1/50)
```
```{r}
relevant_clusters
```

## Manual Corrections

```{r manual-edit, echo=TRUE}
# Example:
# relevant_clusters <- modify_voc_assignment(relevant_clusters, "2-Heptanone (Dimer)", "ClusterXYZ", cluster_stats, ratio = 1/50)
```

## Relevant Peak Tables

```{r select-relevant, echo=FALSE}
selected_clusters <- na.omit(relevant_clusters$cluster)
vocs <- na.omit(relevant_clusters$compound)

peak_table_relevant <- peak_table_corrected[, c("SampleID", "class", "matrix", "patient_id", "patient_condition", "control_level", selected_clusters)]


colnames(peak_table_relevant) <- c("SampleID", "class", "matrix", "patient_id", "patient_condition","control_level", vocs)
```

## Plot

```{r plot-vocs, echo=FALSE}
long_corrected <- melt(
  peak_table_relevant,
  id.vars = c("SampleID", "class", "matrix", "patient_id", "control_level", "patient_condition"),
  variable.name = "VOC",
  value.name = "Intensity"
) %>%
  filter(class == "control") 

long_corrected$control_level <- factor(
  long_corrected$control_level,
  levels = c("LLQC", "LQC", "MQC", "HQC"),
  ordered = TRUE
)

long_corrected$Intensity <- as.numeric(long_corrected$Intensity)
# Plot
ggplot(long_corrected, aes(x = control_level, y = Intensity)) +
  geom_boxplot(color = "#00bfc4", alpha = 0.7) +
  facet_wrap(~ VOC, scales = "free_y") +
  labs(title = "Corrected Intensity in Controls",
       x = "Control Type",
       y = "Intensity") +
  theme_minimal()

```

Select only the ones that we can see clearly that they are well identified (at the end we only need anisole and heptanone dimer)

```{r selecting, echo=FALSE}
# Define selected VOCs
selected_vocs <- c(
  "Anisole (Monomer)",
  "2-Heptanone (Monomer)",
  "2-Heptanone (Dimer)",
  "2-Pentanone (Dimer)"
)


long_selected <- long_corrected %>%
  filter(VOC %in% selected_vocs)

long_selected$Intensity <- as.numeric(long_selected$Intensity)

# Plot
ggplot(long_selected, aes(x = control_level, y = Intensity)) +
  geom_boxplot(color = "#00bfc4", alpha = 0.7) +
  facet_wrap(~ VOC, scales = "free_y") +
  labs(title = "Selected VOCs in Controls",
       x = "Control Type",
       y = "Intensity") +
  theme_minimal()

```


## Save

```{r save-results, echo=FALSE}
dataset_folder <- file.path(latest_folder, "relevant_results")
dir.create(dataset_folder, recursive = TRUE, showWarnings = FALSE)

relevant_clusters <- relevant_clusters %>% 
  filter(compound %in% selected_vocs)
relevant_clusters <- relevant_clusters %>% select(-c(distance, reliable_match))
write.csv(relevant_clusters, file.path(dataset_folder, "relevant_clusters_tgn.csv"), row.names = FALSE)
write.xlsx(relevant_clusters, file.path(dataset_folder, "relevant_clusters_tgn.xlsx"))
cols_to_keep <- c("SampleID", "class", "matrix", "patient_id", "patient_condition", "control_level", selected_vocs)
peak_table_relevant <- peak_table_relevant[, cols_to_keep]

write.csv(peak_table_relevant, file.path(dataset_folder, "peak_table_tgn_relevant.csv"), row.names = FALSE)
write.xlsx(peak_table_relevant, file.path(dataset_folder, "peak_table_tgn_relevant.xlsx")) 
```

